API Fix Pagenation
hibiki31/virty pull request #101
Opened 2023-12-03 07:34 UTC by hibiki31

## ページネーションの追加

- `/api/users` にページネーションとフィルターを追加
- `/api/projects`にページネーションとフィルターを追加
- `/api/nodes`にページネーションとフィルターを追加
- `/api/vms` は変わらず（念のため記載）
- `/api/storages`にページネーション追加
- `/api/images`にページネーション追加
- `/api/networks`にページネーションとフィルターを追加
- `/api/flavors`にページネーションとフィルターを追加

limitを-1にすれば全取得する

フォームの選択肢などで取得する場合はページネーション考えるのだるいので実装

## agentの追加

- タスク実行効率化のため、APIには変化なし

## devcontainerの修正

- 開発環境の修正

## エラーの出ていたAPIの修正

- ユーザの、作成・削除
- フレーバーの、作成・削除
- プロジェクトの、作成・削除

## イメージをダウンロードするAPIの追加

用途：インターネット上のisoファイルをストレージに保存するAPI

エンドポイント：`/api/tasks/images/download`

```json
{
  "storageUuid": "b1377f0a-2475-4138-80ad-7300932a10f6",
  "imageUrl": "http://ftp.riken.go.jp/Linux/ubuntu-releases/jammy/ubuntu-22.04.3-live-server-amd64.iso"
}
```

2023-12-05 15:49 UTC, taso0096 requested changes

2023-12-05 15:49 UTC, taso0096 commented on api/flavor/schemas.py
> +class Flavor(CamelModel):
ページネーション用のcount、dataを持ったクラス名は`XxxPage`に統一して欲しい。
既存のクラス（ここでは`Flavor`）は型的にも元のままにして欲しい。

2023-12-26 02:58 UTC, hibiki31 commented on api/flavor/schemas.py
> +class Flavor(CamelModel):
以下で修正

https://github.com/hibiki31/virty/pull/101/commits/f3cdc12abd6dd36cd347a7b5eb23b47e62608587

2024-04-27 07:02 UTC, taso0096 commented on api/flavor/schemas.py
> +class Flavor(CamelModel):
他のクラスでまだ直っていなさそう？

2024-04-27 07:11 UTC, taso0096 commented on api/flavor/schemas.py
> +class Flavor(CamelModel):
最新コミットでサーバが動いてないのも原因だったっぽい

2024-04-27 07:26 UTC, taso0096 commented
`limit=-1`で500が返ってきてるっぽい

2024-06-04 16:57 UTC, merged